server:
  port: 8888

spring:
  application:
    name: easybuy-config-server

  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL:https://github.com/aayushkodan/easybuy-config}
          username: ${GITHUB_USERNAME:aayushkodan}
          password: ${GITHUB_PASSWORD}
          default-label: main
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

